// Code generated by mockery v2.23.2. DO NOT EDIT.

package redis

import (
	context "context"

	model "github.com/bagusandrian/hitratemechanism/v2/model"
	mock "github.com/stretchr/testify/mock"

	rueidis "github.com/redis/rueidis"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, req
func (_m *MockHandler) Get(ctx context.Context, req model.RequestCheck) (rueidis.RedisResult, model.Response) {
	ret := _m.Called(ctx, req)

	var r0 rueidis.RedisResult
	var r1 model.Response
	if rf, ok := ret.Get(0).(func(context.Context, model.RequestCheck) (rueidis.RedisResult, model.Response)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RequestCheck) rueidis.RedisResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(rueidis.RedisResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RequestCheck) model.Response); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(model.Response)
	}

	return r0, r1
}

// HgetAll provides a mock function with given fields: ctx, req
func (_m *MockHandler) HgetAll(ctx context.Context, req model.RequestCheck) (rueidis.RedisResult, model.Response) {
	ret := _m.Called(ctx, req)

	var r0 rueidis.RedisResult
	var r1 model.Response
	if rf, ok := ret.Get(0).(func(context.Context, model.RequestCheck) (rueidis.RedisResult, model.Response)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RequestCheck) rueidis.RedisResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(rueidis.RedisResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RequestCheck) model.Response); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(model.Response)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandler(t mockConstructorTestingTNewMockHandler) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
